name: redis_Tutorial

# Equivalent docker-compose file for:   docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest

services:
  redisContainer:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"


# Just run:  docker compose up -d